### ISSUE TITLE
Extra space in vector xacro:arg causes crash

### ISSUE THREAD

**Issue by colormotor** [idiap/tinyurdfparser#1]
Hi,
Not a big deal, but the parser crashes if a xacro input file has more than one space separating vector components of an argument. This seems to happen only with args, e.g. `<xacro:arg name="pad_pos" default="0.6 -0.03  0.24"/>`
Only tested this from Python and it gives:
`ValueError: stod: no conversion`

**Comment by maceiras** [comment]
Hi Daniel,

Thanks for letting me know. I will work on that asap.
Best,
Jérémy

**Comment by maceiras** [comment]
It has been fixed in the last update of the repo.
